
import { Resource, Subject, Department, Semester, FileType } from './types';

export const departments: Department[] = [
  { id: "cse", name: "Computer Science & Engineering", code: "CSE" },
  { id: "ee", name: "Electrical Engineering", code: "EE" },
  { id: "me", name: "Mechanical Engineering", code: "ME" },
  { id: "ce", name: "Civil Engineering", code: "CE" },
  { id: "mth", name: "Mathematics", code: "MTH" },
  { id: "phy", name: "Physics", code: "PHY" },
  { id: "chem", name: "Chemistry", code: "CHM" },
  { id: "hss", name: "Humanities & Social Sciences", code: "HSS" },
];

export const subjects: Subject[] = [
  { id: "cs101", name: "Introduction to Programming", code: "CS 101", semester: 1, department: "cse", resourceCount: 24 },
  { id: "cs201", name: "Data Structures", code: "CS 201", semester: 3, department: "cse", resourceCount: 18 },
  { id: "cs301", name: "Algorithms", code: "CS 301", semester: 5, department: "cse", resourceCount: 15 },
  { id: "cs401", name: "Computer Networks", code: "CS 401", semester: 6, department: "cse", resourceCount: 12 },
  { id: "ee101", name: "Basic Electrical Engineering", code: "EE 101", semester: 1, department: "ee", resourceCount: 20 },
  { id: "ee201", name: "Signals and Systems", code: "EE 201", semester: 3, department: "ee", resourceCount: 16 },
  { id: "ma101", name: "Calculus", code: "MA 101", semester: 1, department: "mth", resourceCount: 30 },
  { id: "ma201", name: "Linear Algebra", code: "MA 201", semester: 2, department: "mth", resourceCount: 28 },
  { id: "ma301", name: "Probability & Statistics", code: "MA 301", semester: 3, department: "mth", resourceCount: 22 },
  { id: "hs101", name: "Communication Skills", code: "HS 101", semester: 1, department: "hss", resourceCount: 14 },
];

export const semesters: Semester[] = [
  { id: 1, name: "1st Semester", subjects: subjects.filter(s => s.semester === 1) },
  { id: 2, name: "2nd Semester", subjects: subjects.filter(s => s.semester === 2) },
  { id: 3, name: "3rd Semester", subjects: subjects.filter(s => s.semester === 3) },
  { id: 4, name: "4th Semester", subjects: subjects.filter(s => s.semester === 4) },
  { id: 5, name: "5th Semester", subjects: subjects.filter(s => s.semester === 5) },
  { id: 6, name: "6th Semester", subjects: subjects.filter(s => s.semester === 6) },
  { id: 7, name: "7th Semester", subjects: subjects.filter(s => s.semester === 7) },
  { id: 8, name: "8th Semester", subjects: subjects.filter(s => s.semester === 8) },
];

export const resources: Resource[] = [
  {
    id: "r1",
    title: "Introduction to Programming Complete Notes",
    description: "Comprehensive notes covering all topics from the Introduction to Programming course.",
    subjectId: "cs101",
    subject: "Introduction to Programming",
    semester: 1,
    fileType: FileType.PDF,
    fileUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2128&auto=format&fit=crop",
    tags: ["programming", "basics", "C++", "notes"],
    uploadDate: "2023-08-15T10:30:00Z",
    uploaderId: "u1",
    uploaderName: "Aditya Sharma",
    rating: 4.8,
    downloadCount: 342,
    viewCount: 1024
  },
  {
    id: "r2",
    title: "Data Structures Assignment Solutions",
    description: "Solutions to all assignments for the Data Structures course.",
    subjectId: "cs201",
    subject: "Data Structures",
    semester: 3,
    fileType: FileType.PDF,
    fileUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop",
    tags: ["data structures", "assignments", "solutions"],
    uploadDate: "2023-07-22T14:15:00Z",
    uploaderId: "u2",
    uploaderName: "Priya Patel",
    rating: 4.5,
    downloadCount: 256,
    viewCount: 803
  },
  {
    id: "r3",
    title: "Calculus Formula Sheet",
    description: "A concise formula sheet for Calculus with all important theorems and formulas.",
    subjectId: "ma101",
    subject: "Calculus",
    semester: 1,
    fileType: FileType.PDF,
    fileUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=2070&auto=format&fit=crop",
    tags: ["calculus", "formulas", "mathematics", "cheat sheet"],
    uploadDate: "2023-09-05T09:45:00Z",
    uploaderId: "u3",
    uploaderName: "Rahul Joshi",
    rating: 4.9,
    downloadCount: 478,
    viewCount: 1358
  },
  {
    id: "r4",
    title: "Computer Networks Lecture Slides",
    description: "Complete set of lecture slides from the Computer Networks course.",
    subjectId: "cs401",
    subject: "Computer Networks",
    semester: 6,
    fileType: FileType.PPT,
    fileUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2034&auto=format&fit=crop",
    tags: ["networks", "slides", "TCP/IP", "protocols"],
    uploadDate: "2023-06-30T11:20:00Z",
    uploaderId: "u4",
    uploaderName: "Neha Gupta",
    rating: 4.6,
    downloadCount: 312,
    viewCount: 945
  },
  {
    id: "r5",
    title: "Signals and Systems Solved Problems",
    description: "Collection of solved problems for Signals and Systems with step-by-step solutions.",
    subjectId: "ee201",
    subject: "Signals and Systems",
    semester: 3,
    fileType: FileType.PDF,
    fileUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1581094794329-c8112a89f47e?q=80&w=2070&auto=format&fit=crop",
    tags: ["signals", "systems", "problems", "solutions"],
    uploadDate: "2023-08-10T16:40:00Z",
    uploaderId: "u5",
    uploaderName: "Vikram Singh",
    rating: 4.7,
    downloadCount: 289,
    viewCount: 876
  },
  {
    id: "r6",
    title: "Communication Skills Presentation Template",
    description: "Professional presentation template for Communication Skills class assignments.",
    subjectId: "hs101",
    subject: "Communication Skills",
    semester: 1,
    fileType: FileType.PPT,
    fileUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=2074&auto=format&fit=crop",
    tags: ["communication", "presentation", "template"],
    uploadDate: "2023-07-05T13:25:00Z",
    uploaderId: "u6",
    uploaderName: "Ananya Reddy",
    rating: 4.4,
    downloadCount: 203,
    viewCount: 567
  },
  {
    id: "r7",
    title: "Linear Algebra Exam Preparation Guide",
    description: "Comprehensive guide to prepare for Linear Algebra exams with previous year questions.",
    subjectId: "ma201",
    subject: "Linear Algebra",
    semester: 2,
    fileType: FileType.PDF,
    fileUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?q=80&w=2070&auto=format&fit=crop",
    tags: ["linear algebra", "exam", "preparation", "previous papers"],
    uploadDate: "2023-08-28T15:50:00Z",
    uploaderId: "u7",
    uploaderName: "Karthik Nair",
    rating: 4.8,
    downloadCount: 367,
    viewCount: 1125
  },
  {
    id: "r8",
    title: "Algorithms Lecture Video Series",
    description: "Complete video series explaining key algorithm concepts and implementations.",
    subjectId: "cs301",
    subject: "Algorithms",
    semester: 5,
    fileType: FileType.VIDEO,
    fileUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=2076&auto=format&fit=crop",
    tags: ["algorithms", "video", "lectures", "dynamic programming"],
    uploadDate: "2023-09-12T10:15:00Z",
    uploaderId: "u8",
    uploaderName: "Shreya Kapoor",
    rating: 4.9,
    downloadCount: 421,
    viewCount: 1532
  }
];

export const popularTags = [
  "notes", "assignments", "exams", "slides", "solutions", 
  "programming", "mathematics", "electrical", "cheat sheet", 
  "projects", "research", "tutorials", "books", "videos"
];
